language: python
python:
- '3.6'
install:
- pip install -r dev-requirements.txt
- cd python
- pip install .
script:
- pytest ./test/example_tests/*
deploy:
  provider: pypi
  user: __token__
  password:
    secure: I+gB6GlaKAWzMhdS2LfqNxCFS/zmpELeWoT3vPsQ0miqHUsBqn2sAvrprxCBttTUKpO09Ca0LTBvYFvaiW4nVgFdmzzU8PbOkvNErRw1mVhJxVjWYdRLoKmDafVkrGMLNsE/oNtMZgJCUkChd5eDfPhsufmNBnmRhU/xkcRrgniyzt+Og9442EmPNPnai7KKT3+JqjLiEe2itzicRLCnB4gYf98nXSHO7SB81WFlQO+Gr4+gbDyTK6EZl4THWkBT6fNRWk2dTcIPQBzVv5nCqWAu+TBMAUsMDy1PzL/NougwTSDthwH/9CrWTUewdc8DboRgQTE0jNO3g7KEqofxb/27fFK0Xs2g3pm3DQGf7lBE4o77ms9kx1ZYXkMgy0qtENf2dvtVwc0i67EhwcGDITVXORtWn6LlPeEDhisnrHv/dy+6N0HQB2H5XklNAPGwaEzPCsx7ZgY0RJZ5Y05qzUKNmfCbd92Oi7+kbLIoRbVXSH7doLyMAs9QDeyS3wFaKI93MXaz/RCBEU+PJPTSFkbAP+agowBjOIR13VhVyYoapmHRkGQNaQGXupmo/H1yGXpGfXVDLIc3GDzk10rVNF/GjX1e/uWUkYmlJqzlZCPPB3b0n/Z7Ut2kDdGy53i8FjoXSirsoCrjjthCs80UZc1LLk34heqTS+byFARAI7k=
